spring:
  #################### postgres Configuration #####################################
  datasource:
    url: jdbc:postgresql://localhost:5432/bsf_finance
    username: postgres
    password: pgpassword

  jpa:
    generate-ddl: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public